cassandra:
  image: openzipkin/zipkin-cassandra:1.37.0
  ports:
    - 9042:9042
# The collector process is used for legacy zipkin instrumentation, which log via
# scribe. It can also poll kafka, when the KAFKA_ZOOKEEPER variable is set.
collector:
  image: openzipkin/zipkin-collector:1.37.0
  environment:
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=cassandra
  expose:
    # The scribe thrift api listens on this port
    - 9410
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9900
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - cassandra:storage
# The query process services the UI, and also exposes a POST endpoint that
# instrumentation can send trace data to.
query:
  image: openzipkin/zipkin-query:1.37.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=cassandra
  expose:
    # The http api is mounted at /api/v1
    - 9411
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9901
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - cassandra:storage
web:
  image: openzipkin/zipkin-web:1.37.0
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  expose:
    # Web UI is mounted at the root, and the http api under /api/v1
    - 8080
    # Admin interface is under the http path /admin
    # https://twitter.github.io/twitter-server/Features.html#http-admin-interface
    - 9990
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query
