Document: python-zipkin
Title: Debian python-zipkin Manual
Author: <insert document author here>
Abstract: This manual describes what python-zipkin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-zipkin/python-zipkin.sgml.gz

Format: postscript
Files: /usr/share/doc/python-zipkin/python-zipkin.ps.gz

Format: text
Files: /usr/share/doc/python-zipkin/python-zipkin.text.gz

Format: HTML
Index: /usr/share/doc/python-zipkin/html/index.html
Files: /usr/share/doc/python-zipkin/html/*.html
